language: node_js
node_js:
- stable
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/davidrosenberg/ml2016.git
  - secure: "su6cDBdofjR2nqZF/gqIVJ0IVOVYNcecYbCiMZNTViH7P0iYndE2raZSxtxR/OuRgdrfjYIv1UTicQIKsBqi0MjhwDqB4P1UIb46q2jObC948qAQAl/tgu8lyIke4FJJ/JmHIodIKU01XJUaQN0zFq7A54R9EBS6rsNvos2ylLoBNO5djkbCLGAppstxF87wJ/5pUzEkIv+k1CtxJUZv63cF6i0w2nDz6ey/1Ba8j7kMyK+/NheajewbLMPWlkh4kv3Rc1DFkCrxOYFTw0jFIBksgdc85MxBwvIOifdnX0v1uahl6e7C4coMcJjwpXhhgXtSKOIqpDbulAKk+QQ0vGKgIP6diQZL+9cdKnGKz4CXrbwg51Sks6ivz9z9Myob4H30lNV30JsF4UOkYdFAFJaBm7za5n5T0xCg6q84z1AJ9NuW/XhUOmgPM6S45YrsN4GLNZGsiciT9sdr/zkCMqFDi6svBHGmagSv5VMRvSgR2ds4xtgZsuLpw5XN1bZ9/y4Q/8QVe5sva9sayvoKvFhCnJfqo94Eg91JSTY5lc018fXUSidG7NXFi7MpTIr9gWWAKBPJhcWu9qeDcEid7Z4BnYGXaqiJRsSotPR7TCWZIffjHjHnZDSLHT5oFzn2XlmyL0ijDqlwuuhW9UQ6FVVbBGCKtaiZgu7LCwAehBM="
